version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - volume_data_rabbitmq:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  volume_data_rabbitmq:
    external: false