
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer

server:
  port: 8081

q:
  promotion:
    discount: q.promotion.discount
    free-delivery: q.promotion.free-delivery
x:
  promotion: x.promotion