
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer

server:
  port: 8081

q:
  picture:
    vector: q.picture.vector
    image: q.picture.image
x:
  picture: x.picture

routing-key:
  png: png
  jpg: jpg
  svg: svg