spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: producer

server:
  port: 8080


q:
  hr:
    marketing: q.hr.marketing
    accounting: q.hr.accounting
x:
  hr: x.hr